<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Place;
use Illuminate\Database\Seeder;

class PlaceSeeder extends Seeder
{
    /**
     * Seed the landmarks, restaurants, and attractions of the catalogue.
     */
    public function run(): void
    {
        $cityIds = City::query()->pluck('id', 'name_en');

        foreach ($this->places() as $place) {
            $defaults = $this->practicalDefaults()[$place['category']];
            $city = $place['city'];

            unset($place['city']);

            $attributes = [
                ...$defaults,
                ...$place,
                'city_id' => $cityIds[$city],
                'image' => $this->images()[$place['name_en']] ?? null,
            ];

            Place::query()->updateOrCreate(
                ['city_id' => $attributes['city_id'], 'name_en' => $attributes['name_en']],
                $attributes,
            );
        }
    }

    /**
     * Practical defaults per category, mirroring the existing UI behaviour.
     *
     * @return array<string, array<string, mixed>>
     */
    private function practicalDefaults(): array
    {
        return [
            'landmark' => [
                'opening_hours' => 'يومياً ٩:٠٠ ص – ١١:٠٠ م',
                'prayer_facilities' => true,
                'wheelchair_accessible' => true,
                'closed_friday' => false,
            ],
            'museum' => [
                'opening_hours' => 'الأحد – الخميس ٩:٠٠ ص – ٩:٠٠ م',
                'prayer_facilities' => true,
                'wheelchair_accessible' => true,
                'closed_friday' => true,
            ],
            'heritage' => [
                'opening_hours' => 'يومياً ٨:٠٠ ص – ١١:٠٠ م',
                'prayer_facilities' => true,
                'wheelchair_accessible' => true,
                'closed_friday' => false,
            ],
            'restaurant' => [
                'opening_hours' => 'يومياً ١٢:٠٠ م – ١:٠٠ ص',
                'prayer_facilities' => true,
                'wheelchair_accessible' => true,
                'closed_friday' => false,
            ],
            'park' => [
                'opening_hours' => 'يومياً ٦:٠٠ ص – ١١:٠٠ م',
                'prayer_facilities' => true,
                'wheelchair_accessible' => true,
                'closed_friday' => false,
            ],
            'nature' => [
                'opening_hours' => 'مفتوح دائماً',
                'prayer_facilities' => false,
                'wheelchair_accessible' => false,
                'closed_friday' => false,
            ],
            'beach' => [
                'opening_hours' => 'يومياً ٨:٠٠ ص – ١٠:٠٠ م',
                'prayer_facilities' => true,
                'wheelchair_accessible' => true,
                'closed_friday' => false,
            ],
            'shopping' => [
                'opening_hours' => 'يومياً ١٠:٠٠ ص – ١١:٠٠ م',
                'prayer_facilities' => true,
                'wheelchair_accessible' => true,
                'closed_friday' => false,
            ],
        ];
    }

    /**
     * Freely licensed Wikimedia Commons photography per place.
     *
     * @return array<string, string>
     */
    private function images(): array
    {
        return [
            'Masmak Fortress' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Masmak_Fort_%2812753717253%29.jpg/1280px-Masmak_Fort_%2812753717253%29.jpg',
            'National Museum' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/National_Museum_Riyadh_%286781666263%29.jpg/1280px-National_Museum_Riyadh_%286781666263%29.jpg',
            'Diriyah At-Turaif' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/At-Turaif_District_in_ad-Dir%27iyah_%2812%29.jpg/1280px-At-Turaif_District_in_ad-Dir%27iyah_%2812%29.jpg',
            'Boulevard Riyadh City' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Boulevard_Riyadh_City.jpg/1280px-Boulevard_Riyadh_City.jpg',
            'Kingdom Centre Tower' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Riyadh_Skyline.jpg/1280px-Riyadh_Skyline.jpg',
            'Historic Jeddah' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3e/Al-Balad_commerce%2C_Jeddah.jpg/1280px-Al-Balad_commerce%2C_Jeddah.jpg',
            'King Fahd Fountain' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/BSM_2571.jpg/1280px-BSM_2571.jpg',
            'Al-Rahma Floating Mosque' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Al-Rahmah_Mosque_7_%28cropped%29.jpg/1280px-Al-Rahmah_Mosque_7_%28cropped%29.jpg',
            'Hegra' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/27%2C_Hegra_%28Mada%27in_Salih%29%2C_Saudi_Arabia.jpg/1280px-27%2C_Hegra_%28Mada%27in_Salih%29%2C_Saudi_Arabia.jpg',
            'Elephant Rock' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/86/Elephant_rock%2C_Al-%27Ula.jpg/1280px-Elephant_rock%2C_Al-%27Ula.jpg',
            'Maraya' => 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Al_Ula_9.jpg',
            'Al Soudah' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Cable_car_in_Abha.jpg/1280px-Cable_car_in_Abha.jpg',
            'Al Hada Cable Car' => 'https://upload.wikimedia.org/wikipedia/commons/0/05/Ramada_Al_Hada_Hotel_Telefrique_Station_-_Taif%2C_Saudi_Arabia%2C_%283947435108%29.jpg',
            'Khobar Corniche' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Fishermen_along_khobar_Corniche_%282914401909%29.jpg/1280px-Fishermen_along_khobar_Corniche_%282914401909%29.jpg',
            'King Fahd Causeway' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/King_Fahd_Causeway_bridge_num4.jpg/1280px-King_Fahd_Causeway_bridge_num4.jpg',
            'Souq Al Zal' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Incense_souk_in_downtown_Riyadh_%2812754047044%29.jpg/1280px-Incense_souk_in_downtown_Riyadh_%2812754047044%29.jpg',
            'AlUla Old Town' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Al_Ula_old_town%2C_Saudi_Arabia_2011.jpg/1280px-Al_Ula_old_town%2C_Saudi_Arabia_2011.jpg',
            'Silver Sands Beach' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/AlSaif_Beach_Jeddah_Saudi_Arabia_003.jpg/1280px-AlSaif_Beach_Jeddah_Saudi_Arabia_003.jpg',
            'Al Muftaha Village' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/%D8%A7%D9%84%D9%85%D9%81%D8%AA%D8%A7%D8%AD%D8%A9.jpg/1280px-%D8%A7%D9%84%D9%85%D9%81%D8%AA%D8%A7%D8%AD%D8%A9.jpg',
            'Taif Rose Farms' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/%D8%AD%D8%B5%D8%A7%D8%AF_%D8%A7%D9%84%D9%88%D8%B1%D8%AF_%D8%A7%D9%84%D8%B7%D8%A7%D8%A6%D9%81%D9%8A_%D9%81%D9%8A_%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9_%D8%B3%D9%86%D8%A9_2026%D9%85.jpg/1280px-%D8%AD%D8%B5%D8%A7%D8%AF_%D8%A7%D9%84%D9%88%D8%B1%D8%AF_%D8%A7%D9%84%D8%B7%D8%A7%D8%A6%D9%81%D9%8A_%D9%81%D9%8A_%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9_%D8%B3%D9%86%D8%A9_2026%D9%85.jpg',
            'Wadi Hanifah' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Wadi_Hanifa.jpg/1280px-Wadi_Hanifa.jpg',
            'Al Baik' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/AlBaik%2C_Corniche.jpg/1280px-AlBaik%2C_Corniche.jpg',
            'Najd Village' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bc/Kabsa_%286486384335%29.jpg/1280px-Kabsa_%286486384335%29.jpg',
            'New Abha Park' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d9/Abha_Dam_Lake.jpg/1280px-Abha_Dam_Lake.jpg',
            'Farasan Islands' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Empty_Coast_in_Farasan_Island.jpg/1280px-Empty_Coast_in_Farasan_Island.jpg',
            'Ottoman Castle' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/%D9%82%D9%84%D8%B9%D8%A9_%D8%A7%D9%84%D8%AF%D9%88%D8%B3%D8%B1%D9%8A%D8%A9_3.jpg/1280px-%D9%82%D9%84%D8%B9%D8%A9_%D8%A7%D9%84%D8%AF%D9%88%D8%B3%D8%B1%D9%8A%D8%A9_3.jpg',
            'Fifa Mountains' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Jazan%27s_Fayfa_Mountains_%282025%29.jpg/1280px-Jazan%27s_Fayfa_Mountains_%282025%29.jpg',
            'Jazan North Corniche' => 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Sunset_in_Jazan.jpg/1280px-Sunset_in_Jazan.jpg',
        ];
    }

    /**
     * The places included in the MVP catalogue.
     *
     * @return array<int, array<string, mixed>>
     */
    private function places(): array
    {
        return [
            [
                'city' => 'Riyadh',
                'name' => 'حصن المصمك',
                'name_en' => 'Masmak Fortress',
                'category' => 'heritage',
                'description' => 'قصر طيني تاريخي يعود لمعركة فتح الرياض عام ١٩٠٢.',
                'description_en' => 'A historic mud-brick palace tied to the 1902 Battle of Riyadh.',
                'latitude' => 24.6312,
                'longitude' => 46.7133,
                'ticket_price' => 0,
                'rating' => 4.7,
                'best_time' => 'morning',
                'avg_visit_duration' => 60,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['تاريخ', 'تراث'],
            ],
            [
                'city' => 'Riyadh',
                'name' => 'المتحف الوطني السعودي',
                'name_en' => 'National Museum',
                'category' => 'museum',
                'description' => 'ثماني قاعات تحكي تاريخ الجزيرة العربية.',
                'description_en' => 'Eight galleries telling the history of the Arabian Peninsula.',
                'latitude' => 24.6477,
                'longitude' => 46.7108,
                'ticket_price' => 10,
                'rating' => 4.6,
                'best_time' => 'afternoon',
                'avg_visit_duration' => 120,
                'is_indoor' => true,
                'family_friendly' => true,
                'tags' => ['متحف', 'عائلي'],
            ],
            [
                'city' => 'Riyadh',
                'name' => 'الدرعية التاريخية',
                'name_en' => 'Diriyah At-Turaif',
                'category' => 'heritage',
                'description' => 'موقع تراث عالمي وموطن الدولة السعودية الأولى.',
                'description_en' => 'A UNESCO World Heritage site and the birthplace of the first Saudi state.',
                'latitude' => 24.7336,
                'longitude' => 46.5747,
                'ticket_price' => 50,
                'rating' => 4.8,
                'best_time' => 'evening',
                'avg_visit_duration' => 180,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['يونسكو', 'تراث'],
            ],
            [
                'city' => 'Riyadh',
                'name' => 'بوليفارد رياض سيتي',
                'name_en' => 'Boulevard Riyadh City',
                'category' => 'landmark',
                'description' => 'منطقة ترفيهية ضخمة بمطاعم وعروض وفعاليات.',
                'description_en' => 'A huge entertainment district with restaurants, shows, and events.',
                'latitude' => 24.7736,
                'longitude' => 46.6197,
                'ticket_price' => 25,
                'rating' => 4.7,
                'best_time' => 'night',
                'avg_visit_duration' => 240,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['ترفيه', 'عائلي'],
            ],
            [
                'city' => 'Riyadh',
                'name' => 'برج المملكة',
                'name_en' => 'Kingdom Centre Tower',
                'category' => 'landmark',
                'description' => 'جسر المشاهدة الشهير بإطلالة ٣٠٠ درجة على الرياض.',
                'description_en' => 'The famous Sky Bridge with a 300-degree view over Riyadh.',
                'latitude' => 24.7112,
                'longitude' => 46.6745,
                'ticket_price' => 60,
                'rating' => 4.5,
                'best_time' => 'sunset',
                'avg_visit_duration' => 60,
                'is_indoor' => true,
                'family_friendly' => true,
                'tags' => ['إطلالة', 'أبراج'],
            ],
            [
                'city' => 'Jeddah',
                'name' => 'جدة التاريخية (البلد)',
                'name_en' => 'Historic Jeddah',
                'category' => 'heritage',
                'description' => 'أزقة الحجاز القديمة ومباني الروشان التراثية.',
                'description_en' => 'The old Hijazi alleys and traditional Roshan buildings.',
                'latitude' => 21.4858,
                'longitude' => 39.1869,
                'ticket_price' => 0,
                'rating' => 4.8,
                'best_time' => 'evening',
                'avg_visit_duration' => 150,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['يونسكو', 'تراث'],
            ],
            [
                'city' => 'Jeddah',
                'name' => 'نافورة الملك فهد',
                'name_en' => 'King Fahd Fountain',
                'category' => 'landmark',
                'description' => 'أطول نافورة في العالم على واجهة جدة البحرية.',
                'description_en' => 'The tallest fountain in the world on the Jeddah waterfront.',
                'latitude' => 21.5169,
                'longitude' => 39.1466,
                'ticket_price' => 0,
                'rating' => 4.6,
                'best_time' => 'evening',
                'avg_visit_duration' => 45,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['بحر', 'مجاني'],
            ],
            [
                'city' => 'Jeddah',
                'name' => 'مسجد الرحمة (العائم)',
                'name_en' => 'Al-Rahma Floating Mosque',
                'category' => 'landmark',
                'description' => 'مسجد أبيض يبدو عائماً على البحر الأحمر.',
                'description_en' => 'A white mosque that appears to float on the Red Sea.',
                'latitude' => 21.6353,
                'longitude' => 39.1055,
                'ticket_price' => 0,
                'rating' => 4.7,
                'best_time' => 'dawn',
                'avg_visit_duration' => 45,
                'is_indoor' => true,
                'family_friendly' => true,
                'tags' => ['بحر', 'تصوير'],
            ],
            [
                'city' => 'Jeddah',
                'name' => 'شاطئ السيف',
                'name_en' => 'Silver Sands Beach',
                'category' => 'beach',
                'description' => 'شاطئ خاص بخدمات عائلية وأنشطة بحرية.',
                'description_en' => 'A private beach with family services and water activities.',
                'latitude' => 21.6679,
                'longitude' => 39.1022,
                'ticket_price' => 75,
                'rating' => 4.3,
                'best_time' => 'morning',
                'avg_visit_duration' => 240,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['بحر', 'عائلي'],
            ],
            [
                'city' => 'AlUla',
                'name' => 'الحِجر (مدائن صالح)',
                'name_en' => 'Hegra',
                'category' => 'heritage',
                'description' => 'أول موقع سعودي في قائمة اليونسكو، مقابر نبطية منحوتة.',
                'description_en' => 'Saudi Arabia’s first UNESCO site, with carved Nabataean tombs.',
                'latitude' => 26.7919,
                'longitude' => 37.9553,
                'ticket_price' => 95,
                'rating' => 4.9,
                'best_time' => 'morning',
                'avg_visit_duration' => 180,
                'is_indoor' => false,
                'family_friendly' => true,
                'wheelchair_accessible' => false,
                'prayer_facilities' => true,
                'tags' => ['يونسكو', 'نبطي'],
            ],
            [
                'city' => 'AlUla',
                'name' => 'جبل الفيل',
                'name_en' => 'Elephant Rock',
                'category' => 'nature',
                'description' => 'تكوين صخري عملاق على شكل فيل وسط الرمال.',
                'description_en' => 'A giant rock formation shaped like an elephant.',
                'latitude' => 26.6883,
                'longitude' => 37.9647,
                'ticket_price' => 0,
                'rating' => 4.8,
                'best_time' => 'sunset',
                'avg_visit_duration' => 90,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['تصوير', 'مجاني'],
            ],
            [
                'city' => 'AlUla',
                'name' => 'مرايا',
                'name_en' => 'Maraya',
                'category' => 'landmark',
                'description' => 'أكبر مبنى مغطى بالمرايا في العالم.',
                'description_en' => 'The largest mirrored building in the world.',
                'latitude' => 26.6,
                'longitude' => 37.9,
                'ticket_price' => 40,
                'rating' => 4.7,
                'best_time' => 'evening',
                'avg_visit_duration' => 60,
                'is_indoor' => true,
                'family_friendly' => true,
                'tags' => ['عروض', 'تصوير'],
            ],
            [
                'city' => 'Abha',
                'name' => 'جبل السودة',
                'name_en' => 'Al Soudah',
                'category' => 'nature',
                'description' => 'أعلى قمة في السعودية بإطلالات ضبابية وتلفريك.',
                'description_en' => 'The highest peak in Saudi Arabia, with foggy views and a cable car.',
                'latitude' => 18.2772,
                'longitude' => 42.3731,
                'ticket_price' => 55,
                'rating' => 4.7,
                'best_time' => 'morning',
                'avg_visit_duration' => 180,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['جبال', 'تلفريك'],
            ],
            [
                'city' => 'Abha',
                'name' => 'قرية المفتاحة',
                'name_en' => 'Al Muftaha Village',
                'category' => 'heritage',
                'description' => 'قرية فنية وتراثية بألوان عسير الزاهية.',
                'description_en' => 'An art and heritage village in the vivid colors of Asir.',
                'latitude' => 18.2164,
                'longitude' => 42.5053,
                'ticket_price' => 0,
                'rating' => 4.4,
                'best_time' => 'afternoon',
                'avg_visit_duration' => 90,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['فن', 'تراث'],
            ],
            [
                'city' => 'Taif',
                'name' => 'مزارع الورد الطائفي',
                'name_en' => 'Taif Rose Farms',
                'category' => 'nature',
                'description' => 'مزارع الورد الشهيرة وموسم قطف الورد في أبريل.',
                'description_en' => 'The famous rose farms and the April rose harvest season.',
                'latitude' => 21.2703,
                'longitude' => 40.4158,
                'ticket_price' => 30,
                'rating' => 4.6,
                'best_time' => 'dawn',
                'avg_visit_duration' => 90,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['ورد', 'موسمي'],
            ],
            [
                'city' => 'Taif',
                'name' => 'الهدا والتلفريك',
                'name_en' => 'Al Hada Cable Car',
                'category' => 'nature',
                'description' => 'تلفريك يعبر الجبال المطلة على الطائف.',
                'description_en' => 'A cable car crossing the mountains above Taif.',
                'latitude' => 21.3617,
                'longitude' => 40.2953,
                'ticket_price' => 45,
                'rating' => 4.4,
                'best_time' => 'morning',
                'avg_visit_duration' => 120,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['جبال', 'عائلي'],
            ],
            [
                'city' => 'Khobar',
                'name' => 'كورنيش الخبر',
                'name_en' => 'Khobar Corniche',
                'category' => 'landmark',
                'description' => 'ممشى بحري ممتد بمطاعم ومقاهي وإطلالة على الخليج.',
                'description_en' => 'A long seaside promenade with restaurants, cafés, and Gulf views.',
                'latitude' => 26.2794,
                'longitude' => 50.208,
                'ticket_price' => 0,
                'rating' => 4.6,
                'best_time' => 'evening',
                'avg_visit_duration' => 120,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['بحر', 'مجاني'],
            ],
            [
                'city' => 'Khobar',
                'name' => 'جسر الملك فهد',
                'name_en' => 'King Fahd Causeway',
                'category' => 'landmark',
                'description' => 'الجسر الذي يربط السعودية بالبحرين.',
                'description_en' => 'The causeway linking Saudi Arabia to Bahrain.',
                'latitude' => 26.2083,
                'longitude' => 50.3236,
                'ticket_price' => 0,
                'rating' => 4.5,
                'best_time' => 'sunset',
                'avg_visit_duration' => 60,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['بحر', 'إطلالة'],
            ],
            [
                'city' => 'Riyadh',
                'name' => 'وادي حنيفة',
                'name_en' => 'Wadi Hanifah',
                'category' => 'park',
                'description' => 'وادٍ طبيعي بمسارات مشي ومناطق تنزه.',
                'description_en' => 'A natural valley with walking trails and picnic areas.',
                'latitude' => 24.6333,
                'longitude' => 46.5833,
                'ticket_price' => 0,
                'rating' => 4.4,
                'best_time' => 'morning',
                'avg_visit_duration' => 120,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['طبيعة', 'مجاني'],
            ],
            [
                'city' => 'Riyadh',
                'name' => 'سوق الزل',
                'name_en' => 'Souq Al Zal',
                'category' => 'shopping',
                'description' => 'سوق شعبي للتراث والسجاد والتحف النجدية.',
                'description_en' => 'A traditional market for heritage, carpets, and Najdi antiques.',
                'latitude' => 24.6297,
                'longitude' => 46.7117,
                'ticket_price' => 0,
                'rating' => 4.3,
                'best_time' => 'afternoon',
                'avg_visit_duration' => 90,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['تسوق', 'تراث'],
            ],
            [
                'city' => 'Jeddah',
                'name' => 'مطعم البيك (فرع البلد)',
                'name_en' => 'Al Baik',
                'category' => 'restaurant',
                'description' => 'أشهر مطعم دجاج مقلي في السعودية.',
                'description_en' => 'The most famous fried chicken restaurant in Saudi.',
                'latitude' => 21.4839,
                'longitude' => 39.1877,
                'ticket_price' => null,
                'rating' => 4.7,
                'best_time' => 'noon',
                'avg_visit_duration' => 45,
                'is_indoor' => true,
                'family_friendly' => true,
                'tags' => ['مأكولات', 'شعبي'],
            ],
            [
                'city' => 'Riyadh',
                'name' => 'مطعم نجد القرية',
                'name_en' => 'Najd Village',
                'category' => 'restaurant',
                'description' => 'مأكولات سعودية تقليدية في أجواء نجدية.',
                'description_en' => 'Traditional Saudi cuisine in a Najdi setting.',
                'latitude' => 24.6869,
                'longitude' => 46.6881,
                'ticket_price' => null,
                'rating' => 4.6,
                'best_time' => 'evening',
                'avg_visit_duration' => 75,
                'is_indoor' => true,
                'family_friendly' => true,
                'tags' => ['سعودي', 'عائلي'],
            ],
            [
                'city' => 'AlUla',
                'name' => 'البلدة القديمة بالعلا',
                'name_en' => 'AlUla Old Town',
                'category' => 'heritage',
                'description' => 'متاهة من البيوت الحجرية المرممة والمقاهي.',
                'description_en' => 'A maze of restored stone houses and cafés.',
                'latitude' => 26.6189,
                'longitude' => 37.9189,
                'ticket_price' => 0,
                'rating' => 4.7,
                'best_time' => 'evening',
                'avg_visit_duration' => 120,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['تراث', 'مقاهي'],
            ],
            [
                'city' => 'Abha',
                'name' => 'منتزه أبها الجديدة',
                'name_en' => 'New Abha Park',
                'category' => 'park',
                'description' => 'حديقة عائلية بإطلالات جبلية وألعاب.',
                'description_en' => 'A family park with mountain views and rides.',
                'latitude' => 18.2345,
                'longitude' => 42.4892,
                'ticket_price' => 20,
                'rating' => 4.2,
                'best_time' => 'afternoon',
                'avg_visit_duration' => 150,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['عائلي', 'حديقة'],
            ],
            [
                'city' => 'Jazan',
                'name' => 'جزر فرسان',
                'name_en' => 'Farasan Islands',
                'category' => 'beach',
                'description' => 'أرخبيل بجزر بكر وشعاب مرجانية وشواطئ بيضاء.',
                'description_en' => 'An archipelago of pristine islands, coral reefs, and white beaches.',
                'latitude' => 16.7022,
                'longitude' => 42.1183,
                'ticket_price' => 50,
                'rating' => 4.7,
                'best_time' => 'morning',
                'avg_visit_duration' => 300,
                'is_indoor' => false,
                'family_friendly' => true,
                'wheelchair_accessible' => false,
                'tags' => ['بحر', 'طبيعة'],
            ],
            [
                'city' => 'Jazan',
                'name' => 'القلعة العثمانية',
                'name_en' => 'Ottoman Castle',
                'category' => 'heritage',
                'description' => 'قلعة تاريخية تطل على مدينة جازان ومينائها.',
                'description_en' => 'A historic castle overlooking Jazan city and its port.',
                'latitude' => 16.8917,
                'longitude' => 42.5405,
                'ticket_price' => 0,
                'rating' => 4.4,
                'best_time' => 'sunset',
                'avg_visit_duration' => 60,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['تاريخ', 'إطلالة'],
            ],
            [
                'city' => 'Jazan',
                'name' => 'جبل فيفا',
                'name_en' => 'Fifa Mountains',
                'category' => 'nature',
                'description' => 'قمم جبلية على ارتفاع ٢٠٠٠ متر فوق الغيوم.',
                'description_en' => 'Mountain peaks at 2,000 meters, often above the clouds.',
                'latitude' => 17.2667,
                'longitude' => 43.1167,
                'ticket_price' => 0,
                'rating' => 4.8,
                'best_time' => 'morning',
                'avg_visit_duration' => 180,
                'is_indoor' => false,
                'family_friendly' => true,
                'wheelchair_accessible' => false,
                'tags' => ['جبال', 'تصوير'],
            ],
            [
                'city' => 'Jazan',
                'name' => 'كورنيش جازان الشمالي',
                'name_en' => 'Jazan North Corniche',
                'category' => 'landmark',
                'description' => 'ممشى بحري عائلي بإطلالة على البحر الأحمر.',
                'description_en' => 'A family seaside promenade overlooking the Red Sea.',
                'latitude' => 16.9297,
                'longitude' => 42.5381,
                'ticket_price' => 0,
                'rating' => 4.5,
                'best_time' => 'evening',
                'avg_visit_duration' => 90,
                'is_indoor' => false,
                'family_friendly' => true,
                'tags' => ['بحر', 'عائلي'],
            ],
        ];
    }
}
